[build]
  publish = "dist"
  command = "NODE_OPTIONS=--max_old_space_size=4096 astro build --batch=16"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"